In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)
scores = np.random.randint(50,101,(5,4))

In [3]:
print(scores)

[[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]


In [4]:
scores[3][2]

73

In [5]:
scores[-2:]

array([[85, 89, 73, 52],
       [71, 51, 73, 93]])

In [6]:
scores[0:3,2:4]

array([[64, 92],
       [88, 68],
       [60, 73]])

# TASK-2

In [7]:
np.round(np.mean(scores[:, 0]), 2)

74.6

In [8]:
np.round(np.mean(scores[:, 1]), 2)

69.6

In [9]:
np.round(np.mean(scores[:, 2]), 2)

71.6

In [10]:
np.round(np.mean(scores[:, 3]), 2)

75.6

In [11]:
curve = [5, 3, 7, 2]

In [12]:
curved_scores = scores + curve

In [13]:
curved_scores

array([[93, 81, 71, 94],
       [62, 73, 95, 70],
       [77, 63, 67, 75],
       [90, 92, 80, 54],
       [76, 54, 80, 95]])

In [14]:
row = np.array([])
a_stu = max(curved_scores[0,:])
print(f"best subject score of student {a_stu}")
row = np.append(row,a_stu)

best subject score of student 94


In [15]:
b_stu  = max(curved_scores[1,:])
print(f"best subject score of student {b_stu}")
row = np.append(row,b_stu)

best subject score of student 95


In [16]:
c_stu = max(curved_scores[2,:])
print(f"best subject score of student {c_stu}")
row = np.append(row,c_stu)

best subject score of student 77


In [17]:
d_stu = max(curved_scores[3,:])
print(f"best subject score of student{d_stu}")
row = np.append(row,d_stu)

best subject score of student92


In [18]:
e_stu = max(curved_scores[4,:])
print(f"best subject score of student{e_stu}")
row = np.append(row,e_stu)

best subject score of student95


In [19]:
print(row)

[94. 95. 77. 92. 95.]


In [28]:
row_min = np.min(row)
row_max = np.max(row)
print(row_min,row_max)

77.0 95.0


In [23]:
Normalize = (scores - row_min) / (row_max - row_min)

In [27]:
print(Normalize)

[[ 0.61111111  0.05555556 -0.72222222  0.83333333]
 [-1.11111111 -0.38888889  0.61111111 -0.5       ]
 [-0.27777778 -0.94444444 -0.94444444 -0.22222222]
 [ 0.44444444  0.66666667 -0.22222222 -1.38888889]
 [-0.33333333 -1.44444444 -0.22222222  0.88888889]]


In [31]:
max_index = np.argmax(Normalize)
print(max_index)

19


In [32]:
row, col = np.unravel_index(max_index, Normalize.shape)
print("Student index (row):", row)
print("Subject index (column):", col)

Student index (row): 4
Subject index (column): 3


In [36]:
high_scores = curved_scores[curved_scores > 90]
print(high_scores)

[93 94 95 92 95]
